// Shaker Club — catalogue de cocktails niche + questionnaire
// base: gin | whisky | rhum | agave | vodka | cognac | aperitivo
// strength: 1 léger · 2 équilibré · 3 costaud
// style: speakeasy | tiki | aperitivo | cantina
// bitter: 0..2 · ss: sour | balanced | sweet · notes: herbal spicy smoky floral
// texture: crisp | creamy | sparkling · citrus/sun/berry: fruit tags

const COCKTAILS = [
  { id:'paper-plane', name:'Paper Plane', base:['whisky','aperitivo'], strength:2, style:['speakeasy','aperitivo'], bitter:1, ss:'balanced', notes:[], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#E8672B', glass:'coupe',
    origin:'Sam Ross · Milk & Honey, New York · 2008', tagline:'Quatre parts égales, un équilibre bourbon-amaro d\'une justesse redoutable.',
    ingredients:[['22 ml','bourbon'],['22 ml','Aperol'],['22 ml','Amaro Nonino'],['22 ml','jus de citron frais']],
    steps:['Verser tous les ingrédients dans un shaker rempli de glace.','Shaker fort 12 secondes.','Filtrer deux fois dans une coupe glacée.'], garnish:'Sans garniture, ou un petit avion en papier sur le bord.' },
  { id:'naked-famous', name:'Naked & Famous', base:['agave'], strength:2, style:['cantina'], bitter:1, ss:'balanced', notes:['smoky','herbal'], texture:'crisp', citrus:['lime'], sun:[], berry:[], color:'#F2A93B', glass:'coupe',
    origin:'Joaquín Simó · Death & Co, New York · 2011', tagline:'Le mezcal rencontre la Chartreuse jaune : fumé, herbacé, lumineux.',
    ingredients:[['22 ml','mezcal'],['22 ml','Chartreuse jaune'],['22 ml','Aperol'],['22 ml','jus de citron vert']],
    steps:['Shaker tous les ingrédients avec de la glace.','Filtrer deux fois dans une coupe.'], garnish:'Aucune.' },
  { id:'jungle-bird', name:'Jungle Bird', base:['rhum','aperitivo'], strength:2, style:['tiki'], bitter:1, ss:'balanced', notes:[], texture:'crisp', citrus:['lime'], sun:['pineapple'], berry:[], color:'#C4432B', glass:'tiki',
    origin:'Kuala Lumpur Hilton · 1978', tagline:'Le seul tiki qui ose le Campari. Ananas, rhum noir, amertume.',
    ingredients:[['45 ml','rhum brun (type blackstrap)'],['22 ml','Campari'],['45 ml','jus d\'ananas'],['15 ml','jus de citron vert'],['15 ml','sirop de sucre']],
    steps:['Shaker avec de la glace.','Filtrer sur glace pilée dans un verre tiki ou un tumbler.'], garnish:'Feuille d\'ananas et une tranche d\'ananas.' },
  { id:'penicillin', name:'Penicillin', base:['whisky'], strength:2, style:['speakeasy'], bitter:0, ss:'balanced', notes:['smoky','spicy'], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#D9A23B', glass:'rocks',
    origin:'Sam Ross · Milk & Honey, New York · 2005', tagline:'Miel, gingembre, scotch, et un voile de tourbe flottant en surface.',
    ingredients:[['60 ml','blended scotch'],['22 ml','jus de citron'],['22 ml','sirop miel-gingembre'],['7 ml','scotch d\'Islay (en float)']],
    steps:['Shaker scotch, citron et sirop avec de la glace.','Filtrer sur un gros glaçon dans un verre old fashioned.','Verser délicatement l\'Islay en surface.'], garnish:'Gingembre confit.' },
  { id:'last-word', name:'Last Word', base:['gin'], strength:3, style:['speakeasy'], bitter:0, ss:'sour', notes:['herbal'], texture:'crisp', citrus:['lime'], sun:[], berry:['cherry'], color:'#B9CF5A', glass:'coupe',
    origin:'Detroit Athletic Club · 1916', tagline:'Oublié pendant 50 ans, ressuscité à Seattle. Vert, vif, sans compromis.',
    ingredients:[['22 ml','gin'],['22 ml','Chartreuse verte'],['22 ml','liqueur de marasquin'],['22 ml','jus de citron vert']],
    steps:['Shaker tous les ingrédients avec de la glace.','Filtrer deux fois dans une coupe glacée.'], garnish:'Une cerise au marasquin.' },
  { id:'bijou', name:'Bijou', base:['gin'], strength:3, style:['speakeasy'], bitter:1, ss:'sweet', notes:['herbal'], texture:'crisp', citrus:['orange'], sun:[], berry:[], color:'#C8702A', glass:'coupe',
    origin:'Harry Johnson · années 1890', tagline:'Diamant, rubis, émeraude : gin, vermouth, Chartreuse. Un classique de salon.',
    ingredients:[['30 ml','gin'],['30 ml','vermouth rouge'],['30 ml','Chartreuse verte'],['1 trait','orange bitters']],
    steps:['Remuer à la cuillère avec de la glace 30 secondes.','Filtrer dans une coupe glacée.'], garnish:'Zeste d\'orange exprimé au-dessus du verre.' },
  { id:'division-bell', name:'Division Bell', base:['agave'], strength:2, style:['cantina'], bitter:1, ss:'sour', notes:['smoky'], texture:'crisp', citrus:['lime'], sun:[], berry:['cherry'], color:'#E77A3A', glass:'coupe',
    origin:'Phil Ward · Mayahuel, New York · 2009', tagline:'Un Last Word mexicain : mezcal, Aperol, marasquin.',
    ingredients:[['30 ml','mezcal'],['22 ml','Aperol'],['15 ml','liqueur de marasquin'],['22 ml','jus de citron vert']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Zeste de pamplemousse.' },
  { id:'trinidad-sour', name:'Trinidad Sour', base:['whisky','aperitivo'], strength:2, style:['speakeasy'], bitter:2, ss:'balanced', notes:['spicy'], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#8B2E22', glass:'coupe',
    origin:'Giuseppe González · Clover Club, Brooklyn · 2009', tagline:'45 ml d\'Angostura comme base. Insensé sur le papier, magistral en bouche.',
    ingredients:[['45 ml','Angostura bitters'],['30 ml','sirop d\'orgeat'],['15 ml','rye whiskey'],['22 ml','jus de citron']],
    steps:['Shaker fort avec de la glace.','Filtrer deux fois dans une coupe.'], garnish:'Aucune.' },
  { id:'oaxaca-old-fashioned', name:'Oaxaca Old Fashioned', base:['agave'], strength:3, style:['cantina','speakeasy'], bitter:0, ss:'sweet', notes:['smoky','spicy'], texture:'crisp', citrus:['orange'], sun:[], berry:[], color:'#C9782A', glass:'rocks',
    origin:'Phil Ward · Death & Co, New York · 2007', tagline:'Le cocktail qui a fait entrer le mezcal dans les bars du monde entier.',
    ingredients:[['45 ml','tequila reposado'],['15 ml','mezcal'],['5 ml','sirop d\'agave'],['2 traits','mole bitters (ou Angostura)']],
    steps:['Remuer avec de la glace 30 secondes.','Filtrer sur un gros glaçon.','Flamber un zeste d\'orange au-dessus du verre.'], garnish:'Zeste d\'orange flambé.' },
  { id:'corpse-reviver-2', name:'Corpse Reviver n°2', base:['gin'], strength:2, style:['speakeasy'], bitter:0, ss:'sour', notes:['herbal'], texture:'crisp', citrus:['lemon','orange'], sun:[], berry:[], color:'#F4D58D', glass:'coupe',
    origin:'Harry Craddock · The Savoy, Londres · 1930', tagline:'« Quatre d\'affilée et le cadavre se relève. » Gin, Lillet, une ombre d\'absinthe.',
    ingredients:[['22 ml','gin'],['22 ml','Cointreau'],['22 ml','Lillet blanc'],['22 ml','jus de citron'],['1 rinçage','absinthe']],
    steps:['Rincer une coupe à l\'absinthe, jeter l\'excédent.','Shaker le reste avec de la glace.','Filtrer dans la coupe.'], garnish:'Zeste d\'orange.' },
  { id:'hanky-panky', name:'Hanky Panky', base:['gin'], strength:3, style:['speakeasy'], bitter:2, ss:'sweet', notes:['herbal'], texture:'crisp', citrus:['orange'], sun:[], berry:[], color:'#7A3A26', glass:'coupe',
    origin:'Ada Coleman · The Savoy, Londres · années 1920', tagline:'Le Fernet en trait, créé par la première grande cheffe barmaid de l\'histoire.',
    ingredients:[['45 ml','gin'],['45 ml','vermouth rouge'],['7 ml','Fernet-Branca']],
    steps:['Remuer avec de la glace 30 secondes.','Filtrer dans une coupe glacée.'], garnish:'Zeste d\'orange.' },
  { id:'boulevardier', name:'Boulevardier', base:['whisky','aperitivo'], strength:3, style:['speakeasy','aperitivo'], bitter:2, ss:'sweet', notes:[], texture:'crisp', citrus:['orange'], sun:[], berry:[], color:'#A8341F', glass:'rocks',
    origin:'Erskine Gwynne · Harry\'s Bar, Paris · 1927', tagline:'Le Negroni parisien, bourbon à la place du gin. Plus rond, plus profond.',
    ingredients:[['45 ml','bourbon'],['30 ml','Campari'],['30 ml','vermouth rouge']],
    steps:['Remuer avec de la glace.','Filtrer sur un gros glaçon.'], garnish:'Zeste d\'orange.' },
  { id:'brown-derby', name:'Brown Derby', base:['whisky'], strength:2, style:['speakeasy'], bitter:0, ss:'balanced', notes:[], texture:'crisp', citrus:['grapefruit'], sun:[], berry:[], color:'#E9A25B', glass:'coupe',
    origin:'Vendome Club, Hollywood · années 1930', tagline:'Bourbon, pamplemousse, miel. Trois ingrédients, zéro défaut.',
    ingredients:[['45 ml','bourbon'],['30 ml','jus de pamplemousse'],['15 ml','sirop de miel (2:1)']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Zeste de pamplemousse.' },
  { id:'airmail', name:'Airmail', base:['rhum'], strength:1, style:['tiki'], bitter:0, ss:'balanced', notes:[], texture:'sparkling', citrus:['lime'], sun:[], berry:[], color:'#F2C463', glass:'flute',
    origin:'Cuba · années 1930', tagline:'Un daiquiri au miel allongé au champagne. Célébration des années Bacardi.',
    ingredients:[['45 ml','rhum ambré'],['15 ml','jus de citron vert'],['15 ml','sirop de miel'],['60 ml','champagne ou crémant']],
    steps:['Shaker rhum, citron vert et miel avec de la glace.','Filtrer dans une flûte.','Compléter au champagne.'], garnish:'Aucune, ou un timbre-poste.' },
  { id:'old-cuban', name:'Old Cuban', base:['rhum'], strength:2, style:['speakeasy','tiki'], bitter:0, ss:'balanced', notes:['herbal'], texture:'sparkling', citrus:['lime'], sun:[], berry:[], color:'#CFD68A', glass:'coupe',
    origin:'Audrey Saunders · Pegu Club, New York · 2001', tagline:'Un mojito qui aurait grandi : rhum vieux, menthe, champagne.',
    ingredients:[['45 ml','rhum ambré'],['22 ml','jus de citron vert'],['30 ml','sirop de sucre'],['6','feuilles de menthe'],['2 traits','Angostura'],['top','champagne']],
    steps:['Piler doucement la menthe dans le sirop.','Ajouter rhum, citron vert, bitters, shaker avec glace.','Filtrer deux fois dans une coupe, compléter au champagne.'], garnish:'Feuille de menthe.' },
  { id:'hemingway-daiquiri', name:'Hemingway Daiquiri', base:['rhum'], strength:2, style:['tiki'], bitter:0, ss:'sour', notes:[], texture:'crisp', citrus:['lime','grapefruit'], sun:[], berry:['cherry'], color:'#F7D9C4', glass:'coupe',
    origin:'El Floridita, La Havane · années 1930', tagline:'Le « Papa Doble » : sec, acidulé, pamplemousse et marasquin.',
    ingredients:[['60 ml','rhum blanc'],['22 ml','jus de citron vert'],['15 ml','jus de pamplemousse'],['15 ml','liqueur de marasquin']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe glacée.'], garnish:'Zeste de citron vert.' },
  { id:'clover-club', name:'Clover Club', base:['gin'], strength:2, style:['speakeasy'], bitter:0, ss:'balanced', notes:[], texture:'creamy', citrus:['lemon'], sun:[], berry:['raspberry'], color:'#E2668A', glass:'coupe',
    origin:'Bellevue-Stratford Hotel, Philadelphie · années 1880', tagline:'Framboise, gin, blanc d\'œuf. Mousse soyeuse et rose poudré.',
    ingredients:[['45 ml','gin'],['15 ml','vermouth dry'],['22 ml','jus de citron'],['22 ml','sirop de framboise'],['1','blanc d\'œuf']],
    steps:['Shaker à sec (sans glace) 10 secondes.','Ajouter la glace, shaker de nouveau.','Filtrer deux fois dans une coupe.'], garnish:'Trois framboises sur une pique.' },
  { id:'bramble', name:'Bramble', base:['gin'], strength:2, style:['speakeasy'], bitter:0, ss:'sour', notes:[], texture:'crisp', citrus:['lemon'], sun:[], berry:['blackberry'], color:'#6B2A4B', glass:'rocks',
    origin:'Dick Bradsell · Fred\'s Club, Londres · 1984', tagline:'La mûre coule dans le gin sour sur glace pilée. Londres, années 80.',
    ingredients:[['50 ml','gin'],['25 ml','jus de citron'],['12 ml','sirop de sucre'],['15 ml','crème de mûre']],
    steps:['Shaker gin, citron et sirop.','Filtrer sur glace pilée dans un tumbler.','Verser la crème de mûre en filet sur le dessus.'], garnish:'Mûres fraîches et une tranche de citron.' },
  { id:'chartreuse-swizzle', name:'Chartreuse Swizzle', base:['aperitivo'], strength:2, style:['tiki'], bitter:0, ss:'balanced', notes:['herbal','spicy'], texture:'crisp', citrus:['lime'], sun:['pineapple'], berry:[], color:'#A7C957', glass:'highball',
    origin:'Marcovaldo Dionysos · San Francisco · 2003', tagline:'La Chartreuse en base, l\'ananas en escorte. Le tiki des moines.',
    ingredients:[['45 ml','Chartreuse verte'],['30 ml','jus d\'ananas'],['15 ml','jus de citron vert'],['15 ml','falernum']],
    steps:['Verser dans un highball rempli de glace pilée.','Swizzler (tourner avec un bâton) jusqu\'au givre.'], garnish:'Menthe fraîche et noix de muscade râpée.' },
  { id:'bees-knees', name:'Bee\'s Knees', base:['gin'], strength:2, style:['speakeasy'], bitter:0, ss:'balanced', notes:['floral'], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#F2C14E', glass:'coupe',
    origin:'Prohibition · années 1920', tagline:'Gin, miel, citron. Inventé pour masquer le gin de baignoire, gardé pour sa grâce.',
    ingredients:[['60 ml','gin'],['22 ml','jus de citron'],['22 ml','sirop de miel (2:1)']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Zeste de citron.' },
  { id:'aviation', name:'Aviation', base:['gin'], strength:2, style:['speakeasy'], bitter:0, ss:'sour', notes:['floral'], texture:'crisp', citrus:['lemon'], sun:[], berry:['cherry'], color:'#B9A7D6', glass:'coupe',
    origin:'Hugo Ensslin · Hotel Wallick, New York · 1916', tagline:'Ciel violet pâle : violette, marasquin, gin. Délicat et un peu étrange.',
    ingredients:[['60 ml','gin'],['15 ml','liqueur de marasquin'],['7 ml','crème de violette'],['22 ml','jus de citron']],
    steps:['Shaker avec de la glace.','Filtrer deux fois dans une coupe.'], garnish:'Cerise au fond du verre.' },
  { id:'vieux-carre', name:'Vieux Carré', base:['cognac','whisky'], strength:3, style:['speakeasy'], bitter:1, ss:'sweet', notes:['herbal','spicy'], texture:'crisp', citrus:[], sun:[], berry:[], color:'#8E3B22', glass:'rocks',
    origin:'Walter Bergeron · Hôtel Monteleone, New Orleans · 1938', tagline:'Rye, cognac, Bénédictine. Le Quartier français dans un verre.',
    ingredients:[['30 ml','rye whiskey'],['30 ml','cognac'],['30 ml','vermouth rouge'],['7 ml','Bénédictine'],['1 trait','Peychaud\'s bitters'],['1 trait','Angostura']],
    steps:['Remuer avec de la glace 30 secondes.','Filtrer sur un gros glaçon.'], garnish:'Zeste de citron.' },
  { id:'sazerac', name:'Sazerac', base:['cognac','whisky'], strength:3, style:['speakeasy'], bitter:1, ss:'sweet', notes:['herbal','spicy'], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#B8551F', glass:'rocks',
    origin:'New Orleans · années 1850', tagline:'Le cocktail officiel de New Orleans. Absinthe en rinçage, Peychaud\'s obligatoire.',
    ingredients:[['60 ml','rye whiskey ou cognac'],['1','morceau de sucre'],['3 traits','Peychaud\'s bitters'],['1 rinçage','absinthe']],
    steps:['Rincer un verre old fashioned à l\'absinthe.','Dissoudre le sucre avec les bitters, ajouter le rye, remuer avec glace.','Filtrer dans le verre rincé, sans glace.'], garnish:'Zeste de citron exprimé puis jeté.' },
  { id:'el-diablo', name:'El Diablo', base:['agave'], strength:2, style:['cantina','tiki'], bitter:0, ss:'balanced', notes:['spicy'], texture:'sparkling', citrus:['lime'], sun:[], berry:['blackberry'], color:'#9B2E4F', glass:'highball',
    origin:'Trader Vic · 1946', tagline:'Tequila, cassis, ginger beer. Rouge sombre, piquant, long en bouche.',
    ingredients:[['45 ml','tequila blanco'],['15 ml','crème de cassis'],['15 ml','jus de citron vert'],['top','ginger beer']],
    steps:['Verser tequila, cassis et citron vert dans un highball plein de glace.','Compléter au ginger beer, remuer doucement.'], garnish:'Quartier de citron vert.' },
  { id:'siesta', name:'Siesta', base:['agave','aperitivo'], strength:2, style:['cantina','aperitivo'], bitter:1, ss:'sour', notes:[], texture:'crisp', citrus:['lime','grapefruit'], sun:[], berry:[], color:'#E86A3E', glass:'coupe',
    origin:'Katie Stipe · Flatiron Lounge, New York · 2006', tagline:'Une margarita au Campari et au pamplemousse. La sieste amère.',
    ingredients:[['60 ml','tequila blanco'],['15 ml','Campari'],['15 ml','jus de pamplemousse'],['15 ml','jus de citron vert'],['15 ml','sirop de sucre']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Roue de citron vert.' },
  { id:'toreador', name:'Toreador', base:['agave'], strength:2, style:['cantina'], bitter:0, ss:'balanced', notes:[], texture:'crisp', citrus:['lime'], sun:['stone'], berry:[], color:'#E9A45F', glass:'coupe',
    origin:'Café Royal Cocktail Book · 1937', tagline:'La margarita avant la margarita : tequila et liqueur d\'abricot.',
    ingredients:[['50 ml','tequila blanco'],['25 ml','liqueur d\'abricot'],['15 ml','jus de citron vert']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Zeste de citron vert.' },
  { id:'champs-elysees', name:'Champs-Élysées', base:['cognac'], strength:3, style:['speakeasy'], bitter:0, ss:'balanced', notes:['herbal'], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#B4B85A', glass:'coupe',
    origin:'The Savoy Cocktail Book · 1930', tagline:'Cognac et Chartreuse verte dans un sour élégant. Injustement oublié.',
    ingredients:[['45 ml','cognac'],['15 ml','Chartreuse verte'],['22 ml','jus de citron'],['15 ml','sirop de sucre'],['1 trait','Angostura']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Zeste de citron.' },
  { id:'japanese-cocktail', name:'Japanese Cocktail', base:['cognac'], strength:3, style:['speakeasy'], bitter:0, ss:'sweet', notes:[], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#A8532A', glass:'coupe',
    origin:'Jerry Thomas · 1862', tagline:'Rien de japonais dedans : cognac, orgeat, bitters. Amande et velours.',
    ingredients:[['60 ml','cognac'],['15 ml','sirop d\'orgeat'],['2 traits','Angostura']],
    steps:['Remuer avec de la glace 30 secondes.','Filtrer dans une coupe.'], garnish:'Zeste de citron.' },
  { id:'jack-rose', name:'Jack Rose', base:['cognac'], strength:2, style:['speakeasy'], bitter:0, ss:'sour', notes:[], texture:'crisp', citrus:['lemon'], sun:['apple'], berry:[], color:'#E0614E', glass:'coupe',
    origin:'New Jersey · années 1900', tagline:'Calvados ou applejack, grenadine maison, citron. Rose et croquant.',
    ingredients:[['60 ml','calvados ou applejack'],['22 ml','jus de citron'],['15 ml','grenadine (maison de préférence)']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Fine tranche de pomme.' },
  { id:'pisco-sour', name:'Pisco Sour', base:['cognac'], strength:2, style:['cantina'], bitter:0, ss:'sour', notes:[], texture:'creamy', citrus:['lime'], sun:[], berry:[], color:'#F1E4B5', glass:'rocks',
    origin:'Victor Morris · Lima · années 1920', tagline:'Le sour national du Pérou : pisco, citron vert, mousse et gouttes d\'Angostura.',
    ingredients:[['60 ml','pisco'],['30 ml','jus de citron vert'],['22 ml','sirop de sucre'],['1','blanc d\'œuf'],['3 traits','Angostura']],
    steps:['Shaker à sec, puis avec glace.','Filtrer dans un verre old fashioned.','Déposer les gouttes d\'Angostura sur la mousse.'], garnish:'Les gouttes d\'Angostura font la garniture.' },
  { id:'harvey-wallbanger', name:'Harvey Wallbanger', base:['vodka'], strength:1, style:['tiki'], bitter:0, ss:'sweet', notes:['herbal'], texture:'crisp', citrus:['orange'], sun:[], berry:[], color:'#F5B240', glass:'highball',
    origin:'Californie · années 1970', tagline:'Un screwdriver coiffé de Galliano, vanille et anis. Kitsch assumé.',
    ingredients:[['45 ml','vodka'],['90 ml','jus d\'orange frais'],['15 ml','Galliano (en float)']],
    steps:['Verser vodka et orange dans un highball rempli de glace, remuer.','Verser le Galliano en surface.'], garnish:'Tranche d\'orange et une cerise.' },
  { id:'salty-dog', name:'Salty Dog', base:['vodka'], strength:1, style:['aperitivo'], bitter:0, ss:'sour', notes:[], texture:'crisp', citrus:['grapefruit'], sun:[], berry:[], color:'#F6D7A8', glass:'highball',
    origin:'États-Unis · années 1950', tagline:'Pamplemousse, vodka, bord salé. Le plus sec des longs drinks.',
    ingredients:[['50 ml','vodka'],['100 ml','jus de pamplemousse frais'],['','sel fin pour le bord du verre']],
    steps:['Saler le bord d\'un highball.','Remplir de glace, verser vodka puis pamplemousse, remuer.'], garnish:'Le bord salé et un quartier de pamplemousse.' },
  { id:'godmother', name:'Godmother', base:['vodka'], strength:3, style:['speakeasy'], bitter:0, ss:'sweet', notes:[], texture:'crisp', citrus:[], sun:[], berry:[], color:'#D6A05A', glass:'rocks',
    origin:'États-Unis · années 1970', tagline:'Vodka et amaretto sur glace. Deux ingrédients, amande grillée.',
    ingredients:[['45 ml','vodka'],['22 ml','amaretto']],
    steps:['Verser sur un gros glaçon dans un verre old fashioned.','Remuer quelques secondes.'], garnish:'Aucune.' },
  { id:'vesper', name:'Vesper', base:['vodka','gin'], strength:3, style:['speakeasy'], bitter:0, ss:'balanced', notes:['floral'], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#F3ECD2', glass:'coupe',
    origin:'Ian Fleming · Casino Royale · 1953', tagline:'Trois mesures de gin, une de vodka, une demie de Lillet. Secoué, bien sûr.',
    ingredients:[['60 ml','gin'],['20 ml','vodka'],['10 ml','Lillet blanc']],
    steps:['Shaker avec de la glace (ou remuer, pour les puristes).','Filtrer dans une coupe glacée.'], garnish:'Large zeste de citron.' },
  { id:'chi-chi', name:'Chi-Chi', base:['vodka'], strength:1, style:['tiki'], bitter:0, ss:'sweet', notes:[], texture:'creamy', citrus:[], sun:['pineapple','coconut'], berry:[], color:'#FBF0DC', glass:'tiki',
    origin:'Hawaï · années 1960', tagline:'La piña colada à la vodka. Coco, ananas, transat.',
    ingredients:[['45 ml','vodka'],['90 ml','jus d\'ananas'],['45 ml','crème de coco'],['15 ml','jus de citron vert']],
    steps:['Mixer avec une tasse de glace pilée jusqu\'à texture lisse.','Verser dans un verre tiki ou un highball.'], garnish:'Tranche d\'ananas et cerise.' },
  { id:'lemon-drop', name:'Lemon Drop', base:['vodka'], strength:2, style:['speakeasy'], bitter:0, ss:'sour', notes:[], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#F7E27A', glass:'coupe',
    origin:'Henry\'s Africa, San Francisco · années 1970', tagline:'Vodka, triple sec, citron, bord sucré. Un sour franc et brillant.',
    ingredients:[['45 ml','vodka'],['15 ml','triple sec'],['22 ml','jus de citron'],['15 ml','sirop de sucre']],
    steps:['Sucrer le bord d\'une coupe.','Shaker avec de la glace, filtrer.'], garnish:'Roue de citron.' },
  { id:'blood-and-sand', name:'Blood and Sand', base:['whisky'], strength:2, style:['speakeasy'], bitter:0, ss:'sweet', notes:[], texture:'crisp', citrus:['orange'], sun:[], berry:['cherry'], color:'#B23A3A', glass:'coupe',
    origin:'The Savoy Cocktail Book · 1930', tagline:'Scotch, cerise, vermouth, orange. Un des rares cocktails au scotch qui marchent.',
    ingredients:[['22 ml','blended scotch'],['22 ml','Cherry Heering'],['22 ml','vermouth rouge'],['22 ml','jus d\'orange frais']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Zeste d\'orange.' },
  { id:'rusty-nail', name:'Rusty Nail', base:['whisky'], strength:3, style:['speakeasy'], bitter:0, ss:'sweet', notes:['herbal','spicy'], texture:'crisp', citrus:[], sun:[], berry:[], color:'#C27C2C', glass:'rocks',
    origin:'21 Club, New York · années 1960', tagline:'Scotch et Drambuie. Le digestif préféré du Rat Pack.',
    ingredients:[['45 ml','blended scotch'],['22 ml','Drambuie']],
    steps:['Verser sur un gros glaçon.','Remuer quelques secondes.'], garnish:'Zeste de citron.' },
  { id:'kingston-negroni', name:'Kingston Negroni', base:['rhum','aperitivo'], strength:3, style:['aperitivo'], bitter:2, ss:'sweet', notes:['spicy'], texture:'crisp', citrus:['orange'], sun:[], berry:[], color:'#A2361F', glass:'rocks',
    origin:'Joaquín Simó · Death & Co, New York · 2009', tagline:'Un Negroni au rhum jamaïcain overproof. Funk, banane, amertume.',
    ingredients:[['30 ml','rhum jamaïcain (Smith & Cross)'],['30 ml','Campari'],['30 ml','vermouth rouge']],
    steps:['Remuer avec de la glace.','Filtrer sur un gros glaçon.'], garnish:'Zeste d\'orange.' },
  { id:'corn-n-oil', name:'Corn \'n\' Oil', base:['rhum'], strength:3, style:['tiki'], bitter:1, ss:'sweet', notes:['spicy'], texture:'crisp', citrus:['lime'], sun:[], berry:[], color:'#3B2118', glass:'rocks',
    origin:'Barbade', tagline:'Rhum noir et falernum. Noir comme le pétrole, épicé comme les Caraïbes.',
    ingredients:[['60 ml','rhum blackstrap'],['15 ml','falernum'],['7 ml','jus de citron vert'],['2 traits','Angostura']],
    steps:['Construire dans un verre old fashioned sur glace.','Remuer.'], garnish:'Quartier de citron vert.' },
  { id:'queens-park-swizzle', name:'Queen\'s Park Swizzle', base:['rhum'], strength:2, style:['tiki'], bitter:1, ss:'balanced', notes:['herbal'], texture:'crisp', citrus:['lime'], sun:[], berry:[], color:'#B7D28A', glass:'highball',
    origin:'Queen\'s Park Hotel, Trinidad · années 1920', tagline:'Rhum, menthe, glace pilée et une couche rouge d\'Angostura. Le mojito de Trinidad.',
    ingredients:[['60 ml','rhum demerara'],['30 ml','jus de citron vert'],['22 ml','sirop de sucre'],['8','feuilles de menthe'],['4 traits','Angostura']],
    steps:['Piler doucement la menthe avec le sirop.','Ajouter rhum, citron vert, glace pilée. Swizzler.','Déposer les bitters en surface.'], garnish:'Bouquet de menthe.' },
  { id:'saturn', name:'Saturn', base:['gin'], strength:2, style:['tiki'], bitter:0, ss:'balanced', notes:[], texture:'crisp', citrus:['lemon'], sun:['passion'], berry:[], color:'#F0A13A', glass:'tiki',
    origin:'J. « Popo » Galsini · 1967', tagline:'Le tiki au gin : fruit de la passion, orgeat, falernum.',
    ingredients:[['37 ml','gin'],['15 ml','purée de fruit de la passion'],['15 ml','jus de citron'],['7 ml','falernum'],['7 ml','sirop d\'orgeat']],
    steps:['Shaker avec de la glace pilée.','Verser tel quel dans un verre tiki.'], garnish:'Zeste de citron vert enroulé en anneau.' },
  { id:'painkiller', name:'Painkiller', base:['rhum'], strength:2, style:['tiki'], bitter:0, ss:'sweet', notes:['spicy'], texture:'creamy', citrus:['orange'], sun:['pineapple','coconut'], berry:[], color:'#F1C27A', glass:'tiki',
    origin:'Soggy Dollar Bar, Îles Vierges · 1971', tagline:'Rhum, ananas, orange, coco et muscade râpée. Nagez jusqu\'au bar.',
    ingredients:[['60 ml','rhum brun (Pusser\'s)'],['120 ml','jus d\'ananas'],['30 ml','jus d\'orange'],['30 ml','crème de coco']],
    steps:['Shaker avec de la glace.','Verser sur glace pilée.'], garnish:'Noix de muscade fraîchement râpée.' },
  { id:'adonis', name:'Adonis', base:['aperitivo'], strength:1, style:['aperitivo'], bitter:1, ss:'sweet', notes:[], texture:'crisp', citrus:['orange'], sun:[], berry:[], color:'#C58B3A', glass:'coupe',
    origin:'Waldorf-Astoria, New York · 1884', tagline:'Xérès et vermouth. Un apéritif à 15° qui a le sérieux d\'un Manhattan.',
    ingredients:[['45 ml','xérès fino'],['45 ml','vermouth rouge'],['2 traits','orange bitters']],
    steps:['Remuer avec de la glace 30 secondes.','Filtrer dans une coupe.'], garnish:'Zeste d\'orange.' },
  { id:'bicicletta', name:'Bicicletta', base:['aperitivo'], strength:1, style:['aperitivo'], bitter:2, ss:'balanced', notes:[], texture:'sparkling', citrus:['lemon'], sun:[], berry:[], color:'#E9603A', glass:'highball',
    origin:'Italie du Nord', tagline:'Campari, vin blanc, eau gazeuse. Nommé d\'après les vieux qui rentrent en zigzag.',
    ingredients:[['60 ml','Campari'],['90 ml','vin blanc sec'],['top','eau gazeuse']],
    steps:['Construire dans un verre à vin rempli de glace.','Remuer doucement.'], garnish:'Roue de citron.' },
  { id:'white-negroni', name:'White Negroni', base:['gin','aperitivo'], strength:3, style:['aperitivo'], bitter:2, ss:'balanced', notes:['herbal','floral'], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#EFE0A8', glass:'rocks',
    origin:'Wayne Collins · Bordeaux · 2001', tagline:'Gin, Suze, Lillet. L\'amertume de la gentiane, pâle et sèche.',
    ingredients:[['45 ml','gin'],['30 ml','Suze'],['30 ml','Lillet blanc']],
    steps:['Remuer avec de la glace.','Filtrer sur un gros glaçon.'], garnish:'Zeste de citron.' },
  { id:'twentieth-century', name:'Twentieth Century', base:['gin'], strength:2, style:['speakeasy'], bitter:0, ss:'balanced', notes:[], texture:'crisp', citrus:['lemon'], sun:[], berry:[], color:'#EFDDBE', glass:'coupe',
    origin:'C.A. Tuck · 1937', tagline:'Gin, Lillet, cacao blanc, citron. Nommé d\'après un train de luxe.',
    ingredients:[['45 ml','gin'],['22 ml','Lillet blanc'],['15 ml','crème de cacao blanc'],['22 ml','jus de citron']],
    steps:['Shaker avec de la glace.','Filtrer dans une coupe.'], garnish:'Zeste de citron.' },
  { id:'ramos-gin-fizz', name:'Ramos Gin Fizz', base:['gin'], strength:2, style:['speakeasy'], bitter:0, ss:'sweet', notes:['floral'], texture:'creamy', citrus:['lemon','lime'], sun:[], berry:[], color:'#FBF3E4', glass:'highball',
    origin:'Henry C. Ramos · New Orleans · 1888', tagline:'Douze minutes de shake, une mousse qui dépasse du verre. Fleur d\'oranger et crème.',
    ingredients:[['60 ml','gin'],['15 ml','jus de citron'],['15 ml','jus de citron vert'],['30 ml','sirop de sucre'],['60 ml','crème liquide'],['1','blanc d\'œuf'],['3 traits','eau de fleur d\'oranger'],['top','eau gazeuse']],
    steps:['Shaker à sec tous les ingrédients sauf le soda, 1 minute.','Ajouter la glace, shaker 1 minute de plus.','Filtrer dans un highball, laisser reposer, compléter au soda pour faire monter la mousse.'], garnish:'Aucune : la mousse suffit.' },
];

const SECTIONS = [
  { id:'alcool', label:'Alcools' },
  { id:'saveur', label:'Saveurs' },
  { id:'fruit',  label:'Fruits' },
];

const QUESTIONS = [
  { id:'base', section:'alcool', multi:true, title:'Quels spiritueux te parlent le plus ?', hint:'Choisis-en un ou plusieurs.',
    options:[
      {v:'gin', l:'Gin', d:'Genièvre, botaniques'},
      {v:'whisky', l:'Whisky & bourbon', d:'Céréales, bois, fumée'},
      {v:'rhum', l:'Rhum', d:'Canne, funk, soleil'},
      {v:'agave', l:'Tequila & mezcal', d:'Agave, minéral, fumé'},
      {v:'vodka', l:'Vodka', d:'Net, discret'},
      {v:'cognac', l:'Cognac & brandys', d:'Raisin, pomme, pisco'},
      {v:'aperitivo', l:'Amers & liqueurs', d:'Campari, Chartreuse, xérès'},
    ]},
  { id:'strength', section:'alcool', multi:false, title:'Tu préfères un cocktail…',
    options:[
      {v:3, l:'Costaud', d:'Spirit-forward, servi court'},
      {v:2, l:'Équilibré', d:'Alcool et fraîcheur à égalité'},
      {v:1, l:'Léger', d:'Peu alcoolisé, long à boire'},
    ]},
  { id:'style', section:'alcool', multi:false, title:'Quel bar te fait rêver ?',
    options:[
      {v:'speakeasy', l:'Speakeasy feutré', d:'Cuir, lumière basse, classiques'},
      {v:'tiki', l:'Paillote tiki', d:'Rhum, glace pilée, exotisme'},
      {v:'aperitivo', l:'Terrasse italienne', d:'Apéritif, amertume, 18 h'},
      {v:'cantina', l:'Cantina d\'agave', d:'Mezcal, citron vert, sel'},
    ]},
  { id:'bitter', section:'saveur', multi:false, title:'L\'amertume, Campari, Fernet et compagnie ?',
    options:[
      {v:'love', l:'J\'adore', d:'Plus c\'est amer, mieux c\'est'},
      {v:'some', l:'Une touche', d:'Pour l\'équilibre, pas plus'},
      {v:'no', l:'Non merci', d:'Je préfère éviter'},
    ]},
  { id:'ss', section:'saveur', multi:false, title:'Plutôt acidulé ou plutôt sucré ?',
    options:[
      {v:'sour', l:'Acidulé', d:'Citron, vivacité'},
      {v:'balanced', l:'Entre les deux', d:'Rond mais frais'},
      {v:'sweet', l:'Plutôt sucré', d:'Doux, enveloppant'},
    ]},
  { id:'notes', section:'saveur', multi:true, title:'Ce qui t\'attire dans un verre',
    hint:'Plusieurs réponses possibles.',
    options:[
      {v:'herbal', l:'Herbacé', d:'Chartreuse, menthe, vermouth'},
      {v:'spicy', l:'Épicé', d:'Gingembre, muscade, bitters'},
      {v:'smoky', l:'Fumé', d:'Mezcal, tourbe'},
      {v:'floral', l:'Floral', d:'Violette, fleur d\'oranger, miel'},
      {v:'none', l:'Rien de tout ça', d:'Je veux du direct'},
    ]},
  { id:'texture', section:'saveur', multi:false, title:'Et en bouche ?',
    options:[
      {v:'crisp', l:'Net et frais', d:'Filtré, sans fioriture'},
      {v:'creamy', l:'Onctueux', d:'Blanc d\'œuf, coco, mousse'},
      {v:'sparkling', l:'Pétillant', d:'Champagne, soda, ginger beer'},
    ]},
  { id:'citrus', section:'fruit', multi:true, title:'Tes agrumes',
    hint:'Plusieurs réponses possibles.',
    options:[
      {v:'lemon', l:'Citron jaune'},
      {v:'lime', l:'Citron vert'},
      {v:'grapefruit', l:'Pamplemousse'},
      {v:'orange', l:'Orange'},
      {v:'none', l:'Pas fan des agrumes'},
    ]},
  { id:'sun', section:'fruit', multi:true, title:'Fruits du soleil et du verger',
    hint:'Plusieurs réponses possibles.',
    options:[
      {v:'pineapple', l:'Ananas'},
      {v:'passion', l:'Fruit de la passion'},
      {v:'coconut', l:'Noix de coco'},
      {v:'apple', l:'Pomme'},
      {v:'stone', l:'Abricot, pêche'},
      {v:'none', l:'Aucun'},
    ]},
  { id:'berry', section:'fruit', multi:true, title:'Fruits rouges et noirs',
    hint:'Plusieurs réponses possibles.',
    options:[
      {v:'raspberry', l:'Framboise'},
      {v:'cherry', l:'Cerise, griotte'},
      {v:'blackberry', l:'Mûre, cassis'},
      {v:'none', l:'Aucun'},
    ]},
];

const LABELS = {
  base:{gin:'Gin', whisky:'Whisky', rhum:'Rhum', agave:'Agave', vodka:'Vodka', cognac:'Brandy', aperitivo:'Amers & liqueurs'},
  style:{speakeasy:'Speakeasy', tiki:'Tiki', aperitivo:'Aperitivo', cantina:'Cantina'},
  notes:{herbal:'Herbacé', spicy:'Épicé', smoky:'Fumé', floral:'Floral'},
  texture:{crisp:'Net', creamy:'Onctueux', sparkling:'Pétillant'},
  citrus:{lemon:'Citron', lime:'Citron vert', grapefruit:'Pamplemousse', orange:'Orange'},
  sun:{pineapple:'Ananas', passion:'Passion', coconut:'Coco', apple:'Pomme', stone:'Abricot'},
  berry:{raspberry:'Framboise', cherry:'Cerise', blackberry:'Mûre'},
  ss:{sour:'Acidulé', balanced:'Équilibré', sweet:'Doux'},
  strength:{1:'Léger', 2:'Équilibré', 3:'Costaud'},
  bitter:{0:'Sans amertume', 1:'Amertume légère', 2:'Bien amer'},
  glass:{coupe:'Coupe', rocks:'Old fashioned', highball:'Highball', flute:'Flûte', tiki:'Verre tiki'},
};
